tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: dev_berend
      warehouse: SNOWFLAKE_LEARNING_WH
    prod:
      type: snowflake
      role: accountadmin
      database: tasty_bytes_dbt_db
      schema: prod
      warehouse: SNOWFLAKE_LEARNING_WH